manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: bosch
      url-base: https://github.com/boschsensortec

  group-filter: [+bsec2]

  projects:
    - name: ncs-zigbee
      remote: ncs
      revision: main

    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: v2.9.2
      import:
        name-blocklist:
          - ci-tools
          - hal_st
          - hal_ambiq
          - hal_ethos_u
          - hal_rpi_pico
          - hal_gigadevice
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_cirrus-logic
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_ti
          - loramac-node
          - net-tools
          - edtt
          - trusted-firmware-m
          - sof

    - name: bsec2
      repo-path: Bosch-BSEC2-Library
      remote: bosch
      groups:
        - bsec2
