name: Zigbee-Config

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Match semantic versioning tags
    branches:
      - main
      - master
      - dev
      - '[0-9]*.[0-9]*.[0-9]*_Dev'
      - '[0-9]*.[0-9]*_Dev'
    paths-ignore:
      - '*.md'

env:
  root_dir: BeeLight

jobs:
  build:
    runs-on: ubuntu-24.04
    container: debian:12

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.root_dir }}

      - name: Dependencies
        working-directory: ${{ env.root_dir }}/firmware/app
        run: |
          apt-get update && apt-get install -y curl
          curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o nrfutil
          mkdir -p zigbee
          chmod +x nrfutil
          ./nrfutil install nrf5sdk-tools

      - name: Generate
        working-directory: ${{ env.root_dir }}/firmware/app
        run: |
          ./nrfutil nrf5sdk-tools zigbee production_config zigbee_config.yml zigbee/zigbee_config.hex --offset 0x17a000

      - name : Upload config
        uses: actions/upload-artifact@v4.3.3
        with:
          name: zigbee-config
          path: |
            ${{ env.root_dir }}/firmware/app/zigbee
          if-no-files-found: ignore
